In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path("..").resolve()
sys.path.insert(0, str(PROJECT_ROOT))

from src.pipeline import run_pipeline

In [2]:
summary_full = run_pipeline(mode="full", fetch=False)

2026-04-24 12:08:23,693 [INFO] pipeline — === Pipeline started ===
2026-04-24 12:08:23,694 [INFO] pipeline — Mode: full
2026-04-24 12:08:23,759 [INFO] src.database — Connected to DuckDB: C:\Users\Baku\Desktop\notebooks\Weather Project\Anemoi Weather Project\Weather-Prediction-Project\data\caspian_weather.duckdb
2026-04-24 12:08:23,761 [INFO] src.database —   Schema 'raw' ready.
2026-04-24 12:08:23,762 [INFO] src.database —   Schema 'staging' ready.
2026-04-24 12:08:23,762 [INFO] src.database —   Schema 'analytics' ready.
2026-04-24 12:08:23,768 [INFO] src.database —   Created raw.weather_daily
2026-04-24 12:08:23,771 [INFO] src.database —   Created raw.visibility_daily
2026-04-24 12:08:23,773 [INFO] src.database —   Created raw.forecast_7day
2026-04-24 12:08:23,774 [INFO] pipeline — Skipping API fetch. Using existing raw CSV files.
2026-04-24 12:08:23,774 [INFO] pipeline — Loading raw CSV files into DuckDB.
2026-04-24 12:08:23,832 [INFO] src.database —   Loaded aktau_historical_2019_2024.csv → raw.weather_daily
2026-04-24 12:08:23,885 [INFO] src.database —   Loaded anzali_historical_2019_2024.csv → raw.weather_daily
2026-04-24 12:08:23,936 [INFO] src.database —   Loaded baku_historical_2019_2024.csv → raw.weather_daily
2026-04-24 12:08:23,982 [INFO] src.database —   Loaded makhachkala_historical_2019_2024.csv → raw.weather_daily
2026-04-24 12:08:24,029 [INFO] src.database —   Loaded turkmenbashi_historical_2019_2024.csv → raw.weather_daily
2026-04-24 12:08:24,107 [INFO] src.database —   Loaded aktau_hourly_visibility_2022_2024.csv → raw.visibility_daily (hourly aggregated)
2026-04-24 12:08:24,175 [INFO] src.database —   Loaded anzali_hourly_visibility_2022_2024.csv → raw.visibility_daily (hourly aggregated)
2026-04-24 12:08:24,239 [INFO] src.database —   Loaded baku_hourly_visibility_2022_2024.csv → raw.visibility_daily (hourly aggregated)
2026-04-24 12:08:24,307 [INFO] src.database —   Loaded makhachkala_hourly_visibility_2022_2024.csv → raw.visibility_daily (hourly aggregated)
2026-04-24 12:08:24,372 [INFO] src.database —   Loaded turkmenbashi_hourly_visibility_2022_2024.csv → raw.visibility_daily (hourly aggregated)
2026-04-24 12:08:24,382 [INFO] src.database —   Loaded aktau_forecast_7day.csv → raw.forecast_7day
2026-04-24 12:08:24,390 [INFO] src.database —   Loaded anzali_forecast_7day.csv → raw.forecast_7day
2026-04-24 12:08:24,399 [INFO] src.database —   Loaded baku_forecast_7day.csv → raw.forecast_7day
2026-04-24 12:08:24,412 [INFO] src.database —   Loaded makhachkala_forecast_7day.csv → raw.forecast_7day
2026-04-24 12:08:24,424 [INFO] src.database —   Loaded turkmenbashi_forecast_7day.csv → raw.forecast_7day
2026-04-24 12:08:24,426 [INFO] src.database — Raw data load complete: {'raw.weather_daily': 10960, 'raw.visibility_daily': 5480, 'raw.forecast_7day': 35}
2026-04-24 12:08:24,428 [INFO] pipeline — Running cleaning pipeline: raw → staging.
2026-04-24 12:08:24,429 [INFO] src.cleaning — === Raw → Staging cleaning pipeline ===
2026-04-24 12:08:24,450 [INFO] src.cleaning — Loaded 10960 rows (16440 total nulls)
2026-04-24 12:08:24,451 [INFO] src.cleaning — Adding visibility_is_known flag...
2026-04-24 12:08:24,454 [INFO] src.cleaning —   visibility_is_known: 5480/10960 rows have real visibility (50.0%)
2026-04-24 12:08:24,455 [INFO] src.cleaning — Handling missing values...
2026-04-24 12:08:24,462 [INFO] src.cleaning —   visibility_mean: filled 5480/5480 nulls with 'median'
2026-04-24 12:08:24,467 [INFO] src.cleaning —   visibility_min: filled 5480/5480 nulls with 'median'
2026-04-24 12:08:24,472 [INFO] src.cleaning —   visibility_hours_below_1km: filled 5480/5480 nulls with 'median'
2026-04-24 12:08:24,475 [INFO] src.cleaning — Winsorizing heavy-tailed variables per-city...
2026-04-24 12:08:24,478 [INFO] src.cleaning —   Winsorized precipitation_sum for Anzali: 17 values > 60.0 capped
2026-04-24 12:08:24,481 [INFO] src.cleaning —   Winsorized precipitation_sum for Baku: 1 values > 30.0 capped
2026-04-24 12:08:24,483 [INFO] src.cleaning —   Winsorized precipitation_sum for Aktau: 1 values > 25.0 capped
2026-04-24 12:08:24,486 [INFO] src.cleaning —   Winsorized precipitation_sum for Makhachkala: 1 values > 40.0 capped
2026-04-24 12:08:24,489 [INFO] src.cleaning —   Winsorized snowfall_sum for Anzali: 2 values > 10.0 capped
2026-04-24 12:08:24,494 [INFO] src.cleaning — Total values winsorized: 22
2026-04-24 12:08:24,495 [INFO] src.cleaning — Flagging outliers (IQR method)...
2026-04-24 12:08:24,506 [INFO] src.cleaning —   temperature_2m_max: flagged 0 outliers (0.0%) using iqr method
2026-04-24 12:08:24,521 [INFO] src.cleaning —   temperature_2m_min: flagged 0 outliers (0.0%) using iqr method
2026-04-24 12:08:24,530 [INFO] src.cleaning —   wind_speed_10m_max: flagged 190 outliers (1.7%) using iqr method
2026-04-24 12:08:24,541 [INFO] src.cleaning —   wind_gusts_10m_max: flagged 198 outliers (1.8%) using iqr method
2026-04-24 12:08:24,548 [INFO] src.cleaning —   precipitation_sum: flagged 1520 outliers (13.9%) using iqr method
2026-04-24 12:08:24,556 [INFO] src.cleaning —   surface_pressure_mean: flagged 58 outliers (0.5%) using iqr method
2026-04-24 12:08:24,557 [INFO] src.cleaning — Total outlier flags set: 1966 across 6 columns
2026-04-24 12:08:24,563 [INFO] src.cleaning — Validating date continuity...
2026-04-24 12:08:24,615 [INFO] src.cleaning — Wrote 10960 rows to staging.weather_daily
2026-04-24 12:08:24,625 [INFO] src.cleaning — === Pipeline complete ===
2026-04-24 12:08:24,626 [INFO] src.cleaning —   rows_in             : 10960
2026-04-24 12:08:24,626 [INFO] src.cleaning —   rows_out            : 10960
2026-04-24 12:08:24,627 [INFO] src.cleaning —   missing_filled      : 16440
2026-04-24 12:08:24,627 [INFO] src.cleaning —   missing_remaining   : 0
2026-04-24 12:08:24,628 [INFO] src.cleaning —   values_winsorized   : 22
2026-04-24 12:08:24,628 [INFO] src.cleaning —   outlier_flags_set   : 1966
2026-04-24 12:08:24,628 [INFO] src.cleaning —   date_gaps           : 0
2026-04-24 12:08:24,629 [INFO] src.cleaning —   continuity_status   : ✅ OK
2026-04-24 12:08:24,630 [INFO] pipeline — Running feature engineering pipeline: staging → analytics.
2026-04-24 12:08:24,631 [INFO] src.features — === Building analytics layer ===
2026-04-24 12:08:24,646 [INFO] src.features — Loaded 10960 staging rows
2026-04-24 12:08:24,646 [INFO] src.features — Running full feature pipeline...
2026-04-24 12:08:24,662 [INFO] src.features —   ✓ seasonal features
2026-04-24 12:08:24,676 [INFO] src.features —   ✓ temperature range
2026-04-24 12:08:24,682 [INFO] src.features —   ✓ heating/cooling degree days
2026-04-24 12:08:24,814 [INFO] src.features —   ✓ wave height proxy (SMB)
2026-04-24 12:08:24,848 [INFO] src.features —   ✓ rolling features (7d, 30d)
2026-04-24 12:08:24,874 [INFO] src.features —   ✓ anomaly scores
2026-04-24 12:08:24,889 [INFO] src.features —   ✓ lag features
2026-04-24 12:08:24,890 [INFO] src.features — Feature pipeline complete — 64 columns total
2026-04-24 12:08:24,952 [INFO] src.features —   Wrote analytics.daily_enriched: 10960 rows
2026-04-24 12:08:24,979 [INFO] src.features —   Wrote analytics.monthly_summary: 360 rows
2026-04-24 12:08:25,027 [INFO] pipeline — Quality checks completed.
2026-04-24 12:08:25,028 [INFO] pipeline — [PASS] raw / Row count — 10,960 rows in raw.weather_daily
2026-04-24 12:08:25,029 [INFO] pipeline — [WARNING] raw / Freshness — Latest raw date is 2024-12-31, which is 479 days old
2026-04-24 12:08:25,029 [INFO] pipeline — [PASS] staging / Null ratio — city: 0.00% nulls
2026-04-24 12:08:25,030 [INFO] pipeline — [PASS] staging / Null ratio — date: 0.00% nulls
2026-04-24 12:08:25,030 [INFO] pipeline — [PASS] staging / Null ratio — temperature_2m_max: 0.00% nulls
2026-04-24 12:08:25,031 [INFO] pipeline — [PASS] staging / Null ratio — temperature_2m_min: 0.00% nulls
2026-04-24 12:08:25,032 [INFO] pipeline — [PASS] staging / Null ratio — temperature_2m_mean: 0.00% nulls
2026-04-24 12:08:25,033 [INFO] pipeline — [PASS] staging / Null ratio — apparent_temperature_mean: 0.00% nulls
2026-04-24 12:08:25,033 [INFO] pipeline — [PASS] staging / Null ratio — wind_speed_10m_max: 0.00% nulls
2026-04-24 12:08:25,034 [INFO] pipeline — [PASS] staging / Null ratio — wind_gusts_10m_max: 0.00% nulls
2026-04-24 12:08:25,034 [INFO] pipeline — [PASS] staging / Null ratio — wind_direction_10m_dominant: 0.00% nulls
2026-04-24 12:08:25,035 [INFO] pipeline — [PASS] staging / Null ratio — precipitation_sum: 0.00% nulls
2026-04-24 12:08:25,036 [INFO] pipeline — [PASS] staging / Null ratio — rain_sum: 0.00% nulls
2026-04-24 12:08:25,036 [INFO] pipeline — [PASS] staging / Null ratio — snowfall_sum: 0.00% nulls
2026-04-24 12:08:25,037 [INFO] pipeline — [PASS] staging / Null ratio — weather_code: 0.00% nulls
2026-04-24 12:08:25,038 [INFO] pipeline — [PASS] staging / Null ratio — relative_humidity_2m_mean: 0.00% nulls
2026-04-24 12:08:25,038 [INFO] pipeline — [PASS] staging / Null ratio — dew_point_2m_mean: 0.00% nulls
2026-04-24 12:08:25,039 [INFO] pipeline — [PASS] staging / Null ratio — surface_pressure_mean: 0.00% nulls
2026-04-24 12:08:25,040 [INFO] pipeline — [PASS] staging / Null ratio — shortwave_radiation_sum: 0.00% nulls
2026-04-24 12:08:25,041 [INFO] pipeline — [PASS] staging / Null ratio — visibility_mean: 0.00% nulls
2026-04-24 12:08:25,042 [INFO] pipeline — [PASS] staging / Null ratio — visibility_min: 0.00% nulls
2026-04-24 12:08:25,042 [INFO] pipeline — [PASS] staging / Null ratio — visibility_hours_below_1km: 0.00% nulls
2026-04-24 12:08:25,043 [INFO] pipeline — [PASS] staging / Null ratio — visibility_is_known: 0.00% nulls
2026-04-24 12:08:25,043 [INFO] pipeline — [PASS] staging / Null ratio — temperature_2m_max_is_outlier: 0.00% nulls
2026-04-24 12:08:25,044 [INFO] pipeline — [PASS] staging / Null ratio — temperature_2m_min_is_outlier: 0.00% nulls
2026-04-24 12:08:25,044 [INFO] pipeline — [PASS] staging / Null ratio — wind_speed_10m_max_is_outlier: 0.00% nulls
2026-04-24 12:08:25,045 [INFO] pipeline — [PASS] staging / Null ratio — wind_gusts_10m_max_is_outlier: 0.00% nulls
2026-04-24 12:08:25,048 [INFO] pipeline — [PASS] staging / Null ratio — precipitation_sum_is_outlier: 0.00% nulls
2026-04-24 12:08:25,048 [INFO] pipeline — [PASS] staging / Null ratio — surface_pressure_mean_is_outlier: 0.00% nulls
2026-04-24 12:08:25,049 [INFO] pipeline — [PASS] staging / Date continuity — No gaps above threshold
2026-04-24 12:08:25,049 [INFO] pipeline — [PASS] staging / Value ranges — Temperature values are within expected range
2026-04-24 12:08:25,049 [INFO] pipeline — [PASS] analytics / Feature completeness — All required feature columns are present
2026-04-24 12:08:25,050 [INFO] pipeline — [PASS] analytics / Feature null check — city: 0 null rows
2026-04-24 12:08:25,050 [INFO] pipeline — [PASS] analytics / Feature null check — date: 0 null rows
2026-04-24 12:08:25,051 [INFO] pipeline — [PASS] analytics / Feature null check — year: 0 null rows
2026-04-24 12:08:25,052 [INFO] pipeline — [PASS] analytics / Feature null check — month: 0 null rows
2026-04-24 12:08:25,053 [INFO] pipeline — [PASS] analytics / Feature null check — season: 0 null rows
2026-04-24 12:08:25,054 [INFO] pipeline — [PASS] analytics / Feature null check — is_risk_day: 0 null rows
2026-04-24 12:08:25,057 [INFO] pipeline — [PASS] analytics / Feature null check — wind_speed_10m_max_7d_mean: 0 null rows
2026-04-24 12:08:25,058 [INFO] pipeline — [PASS] analytics / Feature null check — precipitation_sum_7d_mean: 0 null rows
2026-04-24 12:08:25,058 [INFO] pipeline — [PASS] analytics / Feature null check — temperature_2m_mean_7d_mean: 0 null rows
2026-04-24 12:08:25,059 [INFO] pipeline — === Pipeline completed in 1.37 seconds ===

=== Pipeline Summary ===
Mode: full
Database: C:\Users\Baku\Desktop\notebooks\Weather Project\Anemoi Weather Project\Weather-Prediction-Project\data\caspian_weather.duckdb
Raw directory: C:\Users\Baku\Desktop\notebooks\Weather Project\Anemoi Weather Project\Weather-Prediction-Project\data\raw
Duration: 1.37 seconds

Load counts:
  raw.weather_daily: 10,960
  raw.visibility_daily: 5,480
  raw.forecast_7day: 35

Cleaning summary:
  rows_in: 10960
  rows_out: 10960
  missing_filled: 16440
  missing_remaining: 0
  values_winsorized: 22
  outlier_flags_set: 1966
  date_gaps: 0
  continuity_status: ✅ OK

Analytics summary:
  daily_enriched_rows: 10960
  monthly_summary_rows: 360
  feature_columns: 72

=== Quality Check Summary ===
          check_name     stage  status                                              details
           Row count       raw    PASS                     10,960 rows in raw.weather_daily
           Freshness       raw WARNING Latest raw date is 2024-12-31, which is 479 days old
          Null ratio   staging    PASS                                    city: 0.00% nulls
          Null ratio   staging    PASS                                    date: 0.00% nulls
          Null ratio   staging    PASS                      temperature_2m_max: 0.00% nulls
          Null ratio   staging    PASS                      temperature_2m_min: 0.00% nulls
          Null ratio   staging    PASS                     temperature_2m_mean: 0.00% nulls
          Null ratio   staging    PASS               apparent_temperature_mean: 0.00% nulls
          Null ratio   staging    PASS                      wind_speed_10m_max: 0.00% nulls
          Null ratio   staging    PASS                      wind_gusts_10m_max: 0.00% nulls
          Null ratio   staging    PASS             wind_direction_10m_dominant: 0.00% nulls
          Null ratio   staging    PASS                       precipitation_sum: 0.00% nulls
          Null ratio   staging    PASS                                rain_sum: 0.00% nulls
          Null ratio   staging    PASS                            snowfall_sum: 0.00% nulls
          Null ratio   staging    PASS                            weather_code: 0.00% nulls
          Null ratio   staging    PASS               relative_humidity_2m_mean: 0.00% nulls
          Null ratio   staging    PASS                       dew_point_2m_mean: 0.00% nulls
          Null ratio   staging    PASS                   surface_pressure_mean: 0.00% nulls
          Null ratio   staging    PASS                 shortwave_radiation_sum: 0.00% nulls
          Null ratio   staging    PASS                         visibility_mean: 0.00% nulls
          Null ratio   staging    PASS                          visibility_min: 0.00% nulls
          Null ratio   staging    PASS              visibility_hours_below_1km: 0.00% nulls
          Null ratio   staging    PASS                     visibility_is_known: 0.00% nulls
          Null ratio   staging    PASS           temperature_2m_max_is_outlier: 0.00% nulls
          Null ratio   staging    PASS           temperature_2m_min_is_outlier: 0.00% nulls
          Null ratio   staging    PASS           wind_speed_10m_max_is_outlier: 0.00% nulls
          Null ratio   staging    PASS           wind_gusts_10m_max_is_outlier: 0.00% nulls
          Null ratio   staging    PASS            precipitation_sum_is_outlier: 0.00% nulls
          Null ratio   staging    PASS        surface_pressure_mean_is_outlier: 0.00% nulls
     Date continuity   staging    PASS                              No gaps above threshold
        Value ranges   staging    PASS         Temperature values are within expected range
Feature completeness analytics    PASS             All required feature columns are present
  Feature null check analytics    PASS                                    city: 0 null rows
  Feature null check analytics    PASS                                    date: 0 null rows
  Feature null check analytics    PASS                                    year: 0 null rows
  Feature null check analytics    PASS                                   month: 0 null rows
  Feature null check analytics    PASS                                  season: 0 null rows
  Feature null check analytics    PASS                             is_risk_day: 0 null rows
  Feature null check analytics    PASS              wind_speed_10m_max_7d_mean: 0 null rows
  Feature null check analytics    PASS               precipitation_sum_7d_mean: 0 null rows
  Feature null check analytics    PASS             temperature_2m_mean_7d_mean: 0 null rows

Status counts: {'PASS': 40, 'WARNING': 1}

In [3]:
summary_full["quality_checks"]

,check_name,stage,status,details
0,Row count,raw,PASS,"10,960 rows in raw.weather_daily"
1,Freshness,raw,WARNING,"Latest raw date is 2024-12-31, which is 479 da..."
2,Null ratio,staging,PASS,city: 0.00% nulls
3,Null ratio,staging,PASS,date: 0.00% nulls
4,Null ratio,staging,PASS,temperature_2m_max: 0.00% nulls
5,Null ratio,staging,PASS,temperature_2m_min: 0.00% nulls
6,Null ratio,staging,PASS,temperature_2m_mean: 0.00% nulls
7,Null ratio,staging,PASS,apparent_temperature_mean: 0.00% nulls
8,Null ratio,staging,PASS,wind_speed_10m_max: 0.00% nulls
9,Null ratio,staging,PASS,wind_gusts_10m_max: 0.00% nulls
10,Null ratio,staging,PASS,wind_direction_10m_dominant: 0.00% nulls
11,Null ratio,staging,PASS,precipitation_sum: 0.00% nulls
12,Null ratio,staging,PASS,rain_sum: 0.00% nulls
13,Null ratio,staging,PASS,snowfall_sum: 0.00% nulls
14,Null ratio,staging,PASS,weather_code: 0.00% nulls
15,Null ratio,staging,PASS,relative_humidity_2m_mean: 0.00% nulls
16,Null ratio,staging,PASS,dew_point_2m_mean: 0.00% nulls
17,Null ratio,staging,PASS,surface_pressure_mean: 0.00% nulls
18,Null ratio,staging,PASS,shortwave_radiation_sum: 0.00% nulls
19,Null ratio,staging,PASS,visibility_mean: 0.00% nulls
20,Null ratio,staging,PASS,visibility_min: 0.00% nulls
21,Null ratio,staging,PASS,visibility_hours_below_1km: 0.00% nulls
22,Null ratio,staging,PASS,visibility_is_known: 0.00% nulls
23,Null ratio,staging,PASS,temperature_2m_max_is_outlier: 0.00% nulls
24,Null ratio,staging,PASS,temperature_2m_min_is_outlier: 0.00% nulls
25,Null ratio,staging,PASS,wind_speed_10m_max_is_outlier: 0.00% nulls
26,Null ratio,staging,PASS,wind_gusts_10m_max_is_outlier: 0.00% nulls
27,Null ratio,staging,PASS,precipitation_sum_is_outlier: 0.00% nulls
28,Null ratio,staging,PASS,surface_pressure_mean_is_outlier: 0.00% nulls
29,Date continuity,staging,PASS,No gaps above threshold
30,Value ranges,staging,PASS,Temperature values are within expected range
31,Feature completeness,analytics,PASS,All required feature columns are present
32,Feature null check,analytics,PASS,city: 0 null rows
33,Feature null check,analytics,PASS,date: 0 null rows
34,Feature null check,analytics,PASS,year: 0 null rows
35,Feature null check,analytics,PASS,month: 0 null rows
36,Feature null check,analytics,PASS,season: 0 null rows
37,Feature null check,analytics,PASS,is_risk_day: 0 null rows
38,Feature null check,analytics,PASS,wind_speed_10m_max_7d_mean: 0 null rows
39,Feature null check,analytics,PASS,precipitation_sum_7d_mean: 0 null rows
40,Feature null check,analytics,PASS,temperature_2m_mean_7d_mean: 0 null rows

In [4]:
summary_incremental = run_pipeline(mode="incremental", fetch=False)

2026-04-24 12:08:37,077 [INFO] pipeline — === Pipeline started ===
2026-04-24 12:08:37,077 [INFO] pipeline — Mode: incremental
2026-04-24 12:08:37,104 [INFO] src.database — Connected to DuckDB: C:\Users\Baku\Desktop\notebooks\Weather Project\Anemoi Weather Project\Weather-Prediction-Project\data\caspian_weather.duckdb
2026-04-24 12:08:37,105 [INFO] src.database —   Schema 'raw' ready.
2026-04-24 12:08:37,106 [INFO] src.database —   Schema 'staging' ready.
2026-04-24 12:08:37,107 [INFO] src.database —   Schema 'analytics' ready.
2026-04-24 12:08:37,108 [INFO] pipeline — Skipping API fetch. Using existing raw CSV files.
2026-04-24 12:08:37,109 [INFO] pipeline — Loading raw CSV files into DuckDB.
2026-04-24 12:08:37,151 [INFO] src.database —   Loaded aktau_historical_2019_2024.csv → raw.weather_daily
2026-04-24 12:08:37,190 [INFO] src.database —   Loaded anzali_historical_2019_2024.csv → raw.weather_daily
2026-04-24 12:08:37,231 [INFO] src.database —   Loaded baku_historical_2019_2024.csv → raw.weather_daily
2026-04-24 12:08:37,272 [INFO] src.database —   Loaded makhachkala_historical_2019_2024.csv → raw.weather_daily
2026-04-24 12:08:37,313 [INFO] src.database —   Loaded turkmenbashi_historical_2019_2024.csv → raw.weather_daily
2026-04-24 12:08:37,372 [INFO] src.database —   Loaded aktau_hourly_visibility_2022_2024.csv → raw.visibility_daily (hourly aggregated)
2026-04-24 12:08:37,442 [INFO] src.database —   Loaded anzali_hourly_visibility_2022_2024.csv → raw.visibility_daily (hourly aggregated)
2026-04-24 12:08:37,518 [INFO] src.database —   Loaded baku_hourly_visibility_2022_2024.csv → raw.visibility_daily (hourly aggregated)
2026-04-24 12:08:37,581 [INFO] src.database —   Loaded makhachkala_hourly_visibility_2022_2024.csv → raw.visibility_daily (hourly aggregated)
2026-04-24 12:08:37,644 [INFO] src.database —   Loaded turkmenbashi_hourly_visibility_2022_2024.csv → raw.visibility_daily (hourly aggregated)
2026-04-24 12:08:37,659 [INFO] src.database —   Loaded aktau_forecast_7day.csv → raw.forecast_7day
2026-04-24 12:08:37,667 [INFO] src.database —   Loaded anzali_forecast_7day.csv → raw.forecast_7day
2026-04-24 12:08:37,676 [INFO] src.database —   Loaded baku_forecast_7day.csv → raw.forecast_7day
2026-04-24 12:08:37,685 [INFO] src.database —   Loaded makhachkala_forecast_7day.csv → raw.forecast_7day
2026-04-24 12:08:37,694 [INFO] src.database —   Loaded turkmenbashi_forecast_7day.csv → raw.forecast_7day
2026-04-24 12:08:37,696 [INFO] src.database — Raw data load complete: {'raw.weather_daily': 10960, 'raw.visibility_daily': 5480, 'raw.forecast_7day': 70}
2026-04-24 12:08:37,697 [INFO] pipeline — Running cleaning pipeline: raw → staging.
2026-04-24 12:08:37,697 [INFO] src.cleaning — === Raw → Staging cleaning pipeline ===
2026-04-24 12:08:37,714 [INFO] src.cleaning — Loaded 10960 rows (16440 total nulls)
2026-04-24 12:08:37,715 [INFO] src.cleaning — Adding visibility_is_known flag...
2026-04-24 12:08:37,717 [INFO] src.cleaning —   visibility_is_known: 5480/10960 rows have real visibility (50.0%)
2026-04-24 12:08:37,717 [INFO] src.cleaning — Handling missing values...
2026-04-24 12:08:37,723 [INFO] src.cleaning —   visibility_mean: filled 5480/5480 nulls with 'median'
2026-04-24 12:08:37,727 [INFO] src.cleaning —   visibility_min: filled 5480/5480 nulls with 'median'
2026-04-24 12:08:37,732 [INFO] src.cleaning —   visibility_hours_below_1km: filled 5480/5480 nulls with 'median'
2026-04-24 12:08:37,736 [INFO] src.cleaning — Winsorizing heavy-tailed variables per-city...
2026-04-24 12:08:37,740 [INFO] src.cleaning —   Winsorized precipitation_sum for Anzali: 17 values > 60.0 capped
2026-04-24 12:08:37,743 [INFO] src.cleaning —   Winsorized precipitation_sum for Baku: 1 values > 30.0 capped
2026-04-24 12:08:37,746 [INFO] src.cleaning —   Winsorized precipitation_sum for Aktau: 1 values > 25.0 capped
2026-04-24 12:08:37,749 [INFO] src.cleaning —   Winsorized precipitation_sum for Makhachkala: 1 values > 40.0 capped
2026-04-24 12:08:37,751 [INFO] src.cleaning —   Winsorized snowfall_sum for Anzali: 2 values > 10.0 capped
2026-04-24 12:08:37,757 [INFO] src.cleaning — Total values winsorized: 22
2026-04-24 12:08:37,758 [INFO] src.cleaning — Flagging outliers (IQR method)...
2026-04-24 12:08:37,766 [INFO] src.cleaning —   temperature_2m_max: flagged 0 outliers (0.0%) using iqr method
2026-04-24 12:08:37,773 [INFO] src.cleaning —   temperature_2m_min: flagged 0 outliers (0.0%) using iqr method
2026-04-24 12:08:37,780 [INFO] src.cleaning —   wind_speed_10m_max: flagged 190 outliers (1.7%) using iqr method
2026-04-24 12:08:37,786 [INFO] src.cleaning —   wind_gusts_10m_max: flagged 198 outliers (1.8%) using iqr method
2026-04-24 12:08:37,793 [INFO] src.cleaning —   precipitation_sum: flagged 1520 outliers (13.9%) using iqr method
2026-04-24 12:08:37,800 [INFO] src.cleaning —   surface_pressure_mean: flagged 58 outliers (0.5%) using iqr method
2026-04-24 12:08:37,800 [INFO] src.cleaning — Total outlier flags set: 1966 across 6 columns
2026-04-24 12:08:37,803 [INFO] src.cleaning — Validating date continuity...
2026-04-24 12:08:37,897 [INFO] src.cleaning — Wrote 10960 rows to staging.weather_daily
2026-04-24 12:08:37,906 [INFO] src.cleaning — === Pipeline complete ===
2026-04-24 12:08:37,907 [INFO] src.cleaning —   rows_in             : 10960
2026-04-24 12:08:37,908 [INFO] src.cleaning —   rows_out            : 10960
2026-04-24 12:08:37,909 [INFO] src.cleaning —   missing_filled      : 16440
2026-04-24 12:08:37,909 [INFO] src.cleaning —   missing_remaining   : 0
2026-04-24 12:08:37,910 [INFO] src.cleaning —   values_winsorized   : 22
2026-04-24 12:08:37,910 [INFO] src.cleaning —   outlier_flags_set   : 1966
2026-04-24 12:08:37,911 [INFO] src.cleaning —   date_gaps           : 0
2026-04-24 12:08:37,911 [INFO] src.cleaning —   continuity_status   : ✅ OK
2026-04-24 12:08:37,912 [INFO] pipeline — Running feature engineering pipeline: staging → analytics.
2026-04-24 12:08:37,913 [INFO] src.features — === Building analytics layer ===
2026-04-24 12:08:37,923 [INFO] src.features — Loaded 10960 staging rows
2026-04-24 12:08:37,924 [INFO] src.features — Running full feature pipeline...
2026-04-24 12:08:37,939 [INFO] src.features —   ✓ seasonal features
2026-04-24 12:08:37,952 [INFO] src.features —   ✓ temperature range
2026-04-24 12:08:37,958 [INFO] src.features —   ✓ heating/cooling degree days
2026-04-24 12:08:37,997 [INFO] src.features —   ✓ wave height proxy (SMB)
2026-04-24 12:08:38,041 [INFO] src.features —   ✓ rolling features (7d, 30d)
2026-04-24 12:08:38,062 [INFO] src.features —   ✓ anomaly scores
2026-04-24 12:08:38,077 [INFO] src.features —   ✓ lag features
2026-04-24 12:08:38,078 [INFO] src.features — Feature pipeline complete — 64 columns total
2026-04-24 12:08:38,138 [INFO] src.features —   Wrote analytics.daily_enriched: 10960 rows
2026-04-24 12:08:38,155 [INFO] src.features —   Wrote analytics.monthly_summary: 360 rows
2026-04-24 12:08:38,193 [INFO] pipeline — Quality checks completed.
2026-04-24 12:08:38,194 [INFO] pipeline — [PASS] raw / Row count — 10,960 rows in raw.weather_daily
2026-04-24 12:08:38,195 [INFO] pipeline — [WARNING] raw / Freshness — Latest raw date is 2024-12-31, which is 479 days old
2026-04-24 12:08:38,195 [INFO] pipeline — [PASS] staging / Null ratio — city: 0.00% nulls
2026-04-24 12:08:38,196 [INFO] pipeline — [PASS] staging / Null ratio — date: 0.00% nulls
2026-04-24 12:08:38,197 [INFO] pipeline — [PASS] staging / Null ratio — temperature_2m_max: 0.00% nulls
2026-04-24 12:08:38,197 [INFO] pipeline — [PASS] staging / Null ratio — temperature_2m_min: 0.00% nulls
2026-04-24 12:08:38,198 [INFO] pipeline — [PASS] staging / Null ratio — temperature_2m_mean: 0.00% nulls
2026-04-24 12:08:38,198 [INFO] pipeline — [PASS] staging / Null ratio — apparent_temperature_mean: 0.00% nulls
2026-04-24 12:08:38,199 [INFO] pipeline — [PASS] staging / Null ratio — wind_speed_10m_max: 0.00% nulls
2026-04-24 12:08:38,200 [INFO] pipeline — [PASS] staging / Null ratio — wind_gusts_10m_max: 0.00% nulls
2026-04-24 12:08:38,200 [INFO] pipeline — [PASS] staging / Null ratio — wind_direction_10m_dominant: 0.00% nulls
2026-04-24 12:08:38,201 [INFO] pipeline — [PASS] staging / Null ratio — precipitation_sum: 0.00% nulls
2026-04-24 12:08:38,201 [INFO] pipeline — [PASS] staging / Null ratio — rain_sum: 0.00% nulls
2026-04-24 12:08:38,202 [INFO] pipeline — [PASS] staging / Null ratio — snowfall_sum: 0.00% nulls
2026-04-24 12:08:38,202 [INFO] pipeline — [PASS] staging / Null ratio — weather_code: 0.00% nulls
2026-04-24 12:08:38,203 [INFO] pipeline — [PASS] staging / Null ratio — relative_humidity_2m_mean: 0.00% nulls
2026-04-24 12:08:38,203 [INFO] pipeline — [PASS] staging / Null ratio — dew_point_2m_mean: 0.00% nulls
2026-04-24 12:08:38,204 [INFO] pipeline — [PASS] staging / Null ratio — surface_pressure_mean: 0.00% nulls
2026-04-24 12:08:38,204 [INFO] pipeline — [PASS] staging / Null ratio — shortwave_radiation_sum: 0.00% nulls
2026-04-24 12:08:38,205 [INFO] pipeline — [PASS] staging / Null ratio — visibility_mean: 0.00% nulls
2026-04-24 12:08:38,206 [INFO] pipeline — [PASS] staging / Null ratio — visibility_min: 0.00% nulls
2026-04-24 12:08:38,206 [INFO] pipeline — [PASS] staging / Null ratio — visibility_hours_below_1km: 0.00% nulls
2026-04-24 12:08:38,208 [INFO] pipeline — [PASS] staging / Null ratio — visibility_is_known: 0.00% nulls
2026-04-24 12:08:38,209 [INFO] pipeline — [PASS] staging / Null ratio — temperature_2m_max_is_outlier: 0.00% nulls
2026-04-24 12:08:38,210 [INFO] pipeline — [PASS] staging / Null ratio — temperature_2m_min_is_outlier: 0.00% nulls
2026-04-24 12:08:38,210 [INFO] pipeline — [PASS] staging / Null ratio — wind_speed_10m_max_is_outlier: 0.00% nulls
2026-04-24 12:08:38,212 [INFO] pipeline — [PASS] staging / Null ratio — wind_gusts_10m_max_is_outlier: 0.00% nulls
2026-04-24 12:08:38,213 [INFO] pipeline — [PASS] staging / Null ratio — precipitation_sum_is_outlier: 0.00% nulls
2026-04-24 12:08:38,213 [INFO] pipeline — [PASS] staging / Null ratio — surface_pressure_mean_is_outlier: 0.00% nulls
2026-04-24 12:08:38,214 [INFO] pipeline — [PASS] staging / Date continuity — No gaps above threshold
2026-04-24 12:08:38,215 [INFO] pipeline — [PASS] staging / Value ranges — Temperature values are within expected range
2026-04-24 12:08:38,215 [INFO] pipeline — [PASS] analytics / Feature completeness — All required feature columns are present
2026-04-24 12:08:38,216 [INFO] pipeline — [PASS] analytics / Feature null check — city: 0 null rows
2026-04-24 12:08:38,217 [INFO] pipeline — [PASS] analytics / Feature null check — date: 0 null rows
2026-04-24 12:08:38,217 [INFO] pipeline — [PASS] analytics / Feature null check — year: 0 null rows
2026-04-24 12:08:38,218 [INFO] pipeline — [PASS] analytics / Feature null check — month: 0 null rows
2026-04-24 12:08:38,219 [INFO] pipeline — [PASS] analytics / Feature null check — season: 0 null rows
2026-04-24 12:08:38,219 [INFO] pipeline — [PASS] analytics / Feature null check — is_risk_day: 0 null rows
2026-04-24 12:08:38,220 [INFO] pipeline — [PASS] analytics / Feature null check — wind_speed_10m_max_7d_mean: 0 null rows
2026-04-24 12:08:38,221 [INFO] pipeline — [PASS] analytics / Feature null check — precipitation_sum_7d_mean: 0 null rows
2026-04-24 12:08:38,222 [INFO] pipeline — [PASS] analytics / Feature null check — temperature_2m_mean_7d_mean: 0 null rows
2026-04-24 12:08:38,223 [INFO] pipeline — === Pipeline completed in 1.15 seconds ===

=== Pipeline Summary ===
Mode: incremental
Database: C:\Users\Baku\Desktop\notebooks\Weather Project\Anemoi Weather Project\Weather-Prediction-Project\data\caspian_weather.duckdb
Raw directory: C:\Users\Baku\Desktop\notebooks\Weather Project\Anemoi Weather Project\Weather-Prediction-Project\data\raw
Duration: 1.15 seconds

Load counts:
  raw.weather_daily: 10,960
  raw.visibility_daily: 5,480
  raw.forecast_7day: 70

Cleaning summary:
  rows_in: 10960
  rows_out: 10960
  missing_filled: 16440
  missing_remaining: 0
  values_winsorized: 22
  outlier_flags_set: 1966
  date_gaps: 0
  continuity_status: ✅ OK

Analytics summary:
  daily_enriched_rows: 10960
  monthly_summary_rows: 360
  feature_columns: 72

=== Quality Check Summary ===
          check_name     stage  status                                              details
           Row count       raw    PASS                     10,960 rows in raw.weather_daily
           Freshness       raw WARNING Latest raw date is 2024-12-31, which is 479 days old
          Null ratio   staging    PASS                                    city: 0.00% nulls
          Null ratio   staging    PASS                                    date: 0.00% nulls
          Null ratio   staging    PASS                      temperature_2m_max: 0.00% nulls
          Null ratio   staging    PASS                      temperature_2m_min: 0.00% nulls
          Null ratio   staging    PASS                     temperature_2m_mean: 0.00% nulls
          Null ratio   staging    PASS               apparent_temperature_mean: 0.00% nulls
          Null ratio   staging    PASS                      wind_speed_10m_max: 0.00% nulls
          Null ratio   staging    PASS                      wind_gusts_10m_max: 0.00% nulls
          Null ratio   staging    PASS             wind_direction_10m_dominant: 0.00% nulls
          Null ratio   staging    PASS                       precipitation_sum: 0.00% nulls
          Null ratio   staging    PASS                                rain_sum: 0.00% nulls
          Null ratio   staging    PASS                            snowfall_sum: 0.00% nulls
          Null ratio   staging    PASS                            weather_code: 0.00% nulls
          Null ratio   staging    PASS               relative_humidity_2m_mean: 0.00% nulls
          Null ratio   staging    PASS                       dew_point_2m_mean: 0.00% nulls
          Null ratio   staging    PASS                   surface_pressure_mean: 0.00% nulls
          Null ratio   staging    PASS                 shortwave_radiation_sum: 0.00% nulls
          Null ratio   staging    PASS                         visibility_mean: 0.00% nulls
          Null ratio   staging    PASS                          visibility_min: 0.00% nulls
          Null ratio   staging    PASS              visibility_hours_below_1km: 0.00% nulls
          Null ratio   staging    PASS                     visibility_is_known: 0.00% nulls
          Null ratio   staging    PASS           temperature_2m_max_is_outlier: 0.00% nulls
          Null ratio   staging    PASS           temperature_2m_min_is_outlier: 0.00% nulls
          Null ratio   staging    PASS           wind_speed_10m_max_is_outlier: 0.00% nulls
          Null ratio   staging    PASS           wind_gusts_10m_max_is_outlier: 0.00% nulls
          Null ratio   staging    PASS            precipitation_sum_is_outlier: 0.00% nulls
          Null ratio   staging    PASS        surface_pressure_mean_is_outlier: 0.00% nulls
     Date continuity   staging    PASS                              No gaps above threshold
        Value ranges   staging    PASS         Temperature values are within expected range
Feature completeness analytics    PASS             All required feature columns are present
  Feature null check analytics    PASS                                    city: 0 null rows
  Feature null check analytics    PASS                                    date: 0 null rows
  Feature null check analytics    PASS                                    year: 0 null rows
  Feature null check analytics    PASS                                   month: 0 null rows
  Feature null check analytics    PASS                                  season: 0 null rows
  Feature null check analytics    PASS                             is_risk_day: 0 null rows
  Feature null check analytics    PASS              wind_speed_10m_max_7d_mean: 0 null rows
  Feature null check analytics    PASS               precipitation_sum_7d_mean: 0 null rows
  Feature null check analytics    PASS             temperature_2m_mean_7d_mean: 0 null rows

Status counts: {'PASS': 40, 'WARNING': 1}

In [5]:
summary_incremental["quality_checks"]

,check_name,stage,status,details
0,Row count,raw,PASS,"10,960 rows in raw.weather_daily"
1,Freshness,raw,WARNING,"Latest raw date is 2024-12-31, which is 479 da..."
2,Null ratio,staging,PASS,city: 0.00% nulls
3,Null ratio,staging,PASS,date: 0.00% nulls
4,Null ratio,staging,PASS,temperature_2m_max: 0.00% nulls
5,Null ratio,staging,PASS,temperature_2m_min: 0.00% nulls
6,Null ratio,staging,PASS,temperature_2m_mean: 0.00% nulls
7,Null ratio,staging,PASS,apparent_temperature_mean: 0.00% nulls
8,Null ratio,staging,PASS,wind_speed_10m_max: 0.00% nulls
9,Null ratio,staging,PASS,wind_gusts_10m_max: 0.00% nulls
10,Null ratio,staging,PASS,wind_direction_10m_dominant: 0.00% nulls
11,Null ratio,staging,PASS,precipitation_sum: 0.00% nulls
12,Null ratio,staging,PASS,rain_sum: 0.00% nulls
13,Null ratio,staging,PASS,snowfall_sum: 0.00% nulls
14,Null ratio,staging,PASS,weather_code: 0.00% nulls
15,Null ratio,staging,PASS,relative_humidity_2m_mean: 0.00% nulls
16,Null ratio,staging,PASS,dew_point_2m_mean: 0.00% nulls
17,Null ratio,staging,PASS,surface_pressure_mean: 0.00% nulls
18,Null ratio,staging,PASS,shortwave_radiation_sum: 0.00% nulls
19,Null ratio,staging,PASS,visibility_mean: 0.00% nulls
20,Null ratio,staging,PASS,visibility_min: 0.00% nulls
21,Null ratio,staging,PASS,visibility_hours_below_1km: 0.00% nulls
22,Null ratio,staging,PASS,visibility_is_known: 0.00% nulls
23,Null ratio,staging,PASS,temperature_2m_max_is_outlier: 0.00% nulls
24,Null ratio,staging,PASS,temperature_2m_min_is_outlier: 0.00% nulls
25,Null ratio,staging,PASS,wind_speed_10m_max_is_outlier: 0.00% nulls
26,Null ratio,staging,PASS,wind_gusts_10m_max_is_outlier: 0.00% nulls
27,Null ratio,staging,PASS,precipitation_sum_is_outlier: 0.00% nulls
28,Null ratio,staging,PASS,surface_pressure_mean_is_outlier: 0.00% nulls
29,Date continuity,staging,PASS,No gaps above threshold
30,Value ranges,staging,PASS,Temperature values are within expected range
31,Feature completeness,analytics,PASS,All required feature columns are present
32,Feature null check,analytics,PASS,city: 0 null rows
33,Feature null check,analytics,PASS,date: 0 null rows
34,Feature null check,analytics,PASS,year: 0 null rows
35,Feature null check,analytics,PASS,month: 0 null rows
36,Feature null check,analytics,PASS,season: 0 null rows
37,Feature null check,analytics,PASS,is_risk_day: 0 null rows
38,Feature null check,analytics,PASS,wind_speed_10m_max_7d_mean: 0 null rows
39,Feature null check,analytics,PASS,precipitation_sum_7d_mean: 0 null rows
40,Feature null check,analytics,PASS,temperature_2m_mean_7d_mean: 0 null rows

## Pipeline Architecture

```text
┌──────────────────────┐
│ Open-Meteo APIs      │
│ Weather + Visibility │
└──────────┬───────────┘
           │
           ▼
┌──────────────────────┐
│ src/ingestion.py     │
│ Fetch + save raw CSV │
└──────────┬───────────┘
           │
           ▼
┌──────────────────────┐
│ DuckDB raw schema    │
│ raw.weather_daily    │
│ raw.visibility_daily │
└──────────┬───────────┘
           │
           ▼
┌──────────────────────┐
│ src/cleaning.py      │
│ Missing values       │
│ Outlier flags        │
│ Date validation      │
└──────────┬───────────┘
           │
           ▼
┌──────────────────────┐
│ DuckDB staging schema│
│ staging.weather_daily│
└──────────┬───────────┘
           │
           ▼
┌──────────────────────┐
│ src/features.py      │
│ Rolling features     │
│ Seasonal features    │
│ Risk labels          │
└──────────┬───────────┘
           │
           ▼
┌──────────────────────┐
│ DuckDB analytics     │
│ daily_enriched       │
│ monthly_summary      │
└──────────┬───────────┘
           │
           ▼
┌──────────────────────┐
│ src/quality_checks.py│
│ Pass / Warning / Fail│
└──────────────────────┘